### ISSUE TITLE
CHM13 GATK Resource bundle

### ISSUE THREAD

**Issue by JosephLalli** [schatzlab/t2t-chm13-chry#1]
Hi there,

I see that the GATK resource bundle is available on AnViL (eg: gs://fc-47de7dae-e8e6-429c-b760-b4ba49136eee/resources/chm13/resources-broad-hg38-v0-Mills_and_1000G_gold_standard.indels.hg38.t2t-chm13-v1.0.vcf.gz)

Are these files available for download anywhere else? I can't seem to find them, and I am not able to extract them from the AnViL environment.

Thanks,
Joe Lalli

**Comment by dtaylo95** [comment]
Hi Joe,

The GATK resource bundle lifted from GRCh38 to T2T-CHM13v2.0 has been added to the AWS bucket [here](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=T2T/CHM13/assemblies/variants/GATK_CHM13v2.0_Resource_Bundle/)

**Comment by mschatz** [comment]
Thanks!!!

**Comment by JosephLalli** [comment]
Thanks everyone!
